Add warnings for main branch helm chart installation deprecation (#834)
## Changes

We don't support main branch helm chart installation method since it is
prone to referencing images in our releases that doesn't work with helm
charts in main (development) branch. We plan to deprecate this
installation method (1, 2026), and we want to warn users ahead of time
for them to migrate to support installation methods.

- Added warnings in README / NOTES.txt, and added a label in node.yaml
for node pods installed via main branch helm charts.
- Added gating of NOTES warning / label via isHelmRepo in values.yaml,
which is set to true on helm_publish workflow


## Testing

<details>
<summary>Test commands</summary>

```sh
# Main branch charts have label / warning
helm template charts/aws-mountpoint-s3-csi-driver | grep "chart-source"
# output:        s3.csi.aws.com/chart-source: "github-main"
helm install --dry-run=client --generate-name charts/aws-mountpoint-s3-csi-driver | grep "WARNING"
# output: WARNING: You are installing from a GitHub branch.

# sed and grep
sed -i 's/^isHelmRepo: false/isHelmRepo: true/' charts/aws-mountpoint-s3-csi-driver/values.yaml
grep '^isHelmRepo: true' charts/aws-mountpoint-s3-csi-driver/values.yaml
# output: isHelmRepo: true

# Published charts show no warnings / labels
helm template charts/aws-mountpoint-s3-csi-driver | grep -E "chart-source|WARNING"
# output: empty
helm install --dry-run=client --generate-name charts/aws-mountpoint-s3-csi-driver | grep "WARNING"
# output: empty
```

</details>

### Other considerations
- Not added instructions for ArgoCD/FluxCD or other usages to use Helm
Repository installation method (e.g.
[here](https://fluxcd.io/flux/guides/helmreleases/#helm-repository))
rather than Git Repository installation method (i.e. use our helm repo
https://awslabs.github.io/mountpoint-s3-csi-driver link rather than
github link), as I haven't confirmed this usage method.
- We could add `_helpers.tpl` entry if we think `if and (not
.Values.isHelmRepo) (not .Values.isEKSAddon)` is too long later
- yq removes line breaks, so used sed to workaround (unless there are
better alternatives?)


### Deprecation code to add

We can add the deprecation change on (or slightly after) September 1,
2026, by 1/ removing deprecation date references and 2/ adding this code
to the top of node.yaml:

```yaml
{{- if and (not .Values.isHelmRepo) (not .Values.isEKSAddon) -}}
{{- fail `

ERROR: This Helm chart cannot be installed directly from the GitHub main branch.

Supported installation methods:
  - Helm repository: helm repo add aws-mountpoint-s3-csi-driver https://awslabs.github.io/mountpoint-s3-csi-driver
  - EKS Addon: https://docs.aws.amazon.com/eks/latest/userguide/s3-csi.html

See https://github.com/awslabs/mountpoint-s3-csi-driver#installation for details.
` -}}
{{- end -}}
```

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

---------

Signed-off-by: Jensen Tong <jetong@amazon.com>
Co-authored-by: Jensen Tong <jetong@amazon.com>