Deprecate GitHub branch Helm chart installation method (#931)
> [!NOTE]
> To merge on September 1, 2026 as promised in the pinned GitHub issue.

### Description of changes

*Issue #, if available:*
https://github.com/awslabs/mountpoint-s3-csi-driver/issues/859

- Add `unsupportedDevInstall` flag for dev bypass (Naming TBD)
- Fail in helm render if not using Helm / EKS Addon / dev installation
methods
- Add helm-dev `INSTALLATION_TYPE`, add field to user agent with test
edits
- Warn users if they are on dev installation type in node logs and in
helm install (NOTES.txt).

Development breaking change: Developers must use `--set
unsupportedDevInstall=true ` flag from now on:
```
helm upgrade --install aws-mountpoint-s3-csi-driver \
    --namespace kube-system \
    --set unsupportedDevInstall=true \
    ...
```
(No changes if you use mp-dev.sh script)

### Testing

1: Helm render
```
helm template charts/aws-mountpoint-s3-csi-driver
Error: execution error at (aws-mountpoint-s3-csi-driver/templates/node.yaml:2:4):

ERROR: This Helm chart cannot be installed directly from GitHub main branch, as it may reference unreleased images.
...
```

2: verify-helm-images / helm.sh tests will be covered in GitHub tests.

3: upgrade tests (no inputs for latest release -> source tests, ran on
[jet-tong:chore/deprecate-main-branch-helm-chart-sept-1-2026](https://github.com/jet-tong/mountpoint-s3-csi-driver/tree/chore/deprecate-main-branch-helm-chart-sept-1-2026)
branch):
https://github.com/jet-tong/mountpoint-s3-csi-driver/actions/runs/33090856790

4: Unit tests for the user agent part

(Will skip testing the warning log in driver.go that mirrors NOTES.txt
warning, it's for unsupportedDevInstall flag users only)

5: Tested k8s resources not updated when installing with the failure -
ran  `./dev/mp-dev.sh deploy-helm-chart` without the
unsupportedDevInstall line, controller didn't get restarted/updated,
with the Error: UPGRADE FAILED: execution error failure. The failure
fails during rendering stage, which is before anything gets sent to
kubernetes.
[Source](https://helm.sh/docs/chart_template_guide/getting_started/#:~:text=When%20Helm%20evaluates%20a%20chart%2C%20it%20will%20send%20all%20of%20the%20files%20in%20the%20templates/%20directory%20through%20the%20template%20rendering%20engine.%20It%20then%20collects%20the%20results%20of%20those%20templates%20and%20sends%20them%20on%20to%20Kubernetes).

---

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

---------

Signed-off-by: Jensen Tong <jetong@amazon.com>