PodMounter: Fix ReadOnlyMany access mode (#423)
*Issue #, if available:* N/A

*Description of changes:* Currently, PodMounter fails to work with
`ReadOnlyMany` access mode with error:

```
Error: Mount options: --read-only are ignored with FUSE fd mount point.Mount options should be passed while performing `mount` syscall in the caller process.
```

Fix: Remove `--read-only` flag when it is set

Also, added e2e tests for ReadOnlyMany case to validate that the fix
worked.


By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.