Update CI driver uninstall step to be skipped if install was skipped (#716)
*Issue #, if available:*

*Description of changes:*

Where the configuration to access a cluster is not configured (for
example, due to failed login or failed cluster creation), uninstalling
the driver will always fail.

For example, a recent run failed
(https://github.com/awslabs/mountpoint-s3-csi-driver/actions/runs/22457592250/job/65043641401#step:11:120)
with the following:

```
error: stat /home/runner/work/mountpoint-s3-csi-driver/mountpoint-s3-csi-driver/tests/e2e-kubernetes/scripts/../csi-test-artifacts/s3-csi-cluster-eksctl-amazonlinux2023-x86-1-29.kubeconfig: no such file or directory
```

In order to simplify output when CI fails, this change adds a condition
to skip driver uninstall if we cannot access the cluster.

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

Signed-off-by: Daniel Carl Jones <djonesoa@amazon.com>